baseURL = "/"
languageCode = "en-us"
title = "Mr Augustus - A Purveyor of Fine Blogs"
theme = "gohugo-theme-ananke"
publishDir = "public"

[params]
  description = "20 Years+ in the Tech Business, old enough to speak for myself, young enough to hear high frequencies"
  facebook = ""
  twitter = "https://twitter.com/glennaugustus"
  instagram = ""
  youtube = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/cairns-sunset-2017.jpg"
  
